### ISSUE TITLE
How to Compress video?

### ISSUE THREAD

**Issue by jagdalemahesh9** [protonemedia/laravel-ffmpeg#293]
I want to compress the video. how I can compress?

**Comment by Babiute** [comment]
Hey @jagdalemahesh9 

Try to elaborate your questioning better, as we do not know where you are having difficulty with your question.
What have you managed to do? What is the error you are having?
We are here to help, but we need to better understand what kind of help you need.

**Comment by jagdalemahesh9** [comment]
Hello,
I want to reduce video file size.

Thanks,
Mahesh J.

**Comment by Babiute** [comment]
Well.
You keep giving us very little to be able to help you. But I will try.
The final size of the video depends on several factors, but I think two are the most important: The video and audio bitrate.
By setting the video bitrate to 500 kbps and the audio bitrate to 126kbps for example, your video will have, on average, 626 kilobits per second.
With this you can estimate, before processing, the final file size by algebraism.
It should be noted that these values ​​are set for the output video. So, if the input video is a video with a lower bitrate than the one defined, the final video will be larger than the input video, generating an effect contrary to the desired one (assuming we are only concerned with the size of the video).
Therefore, some validations are necessary in the input video so that you know whether or not it will be necessary to reduce its size.
Another point to note is that there is no miracle in reducing the size of a video. If you reduce its size, you will lose quality. Therefore, you have to test these values ​​until you reach the values ​​that you think are ideal for your videos.
That said, a basic read in the manual for this package would be enough, but anyway, follow the basic code for converting a video with the parameters I have informed.

```php
          FFMpeg::fromDisk('disk_from')
                ->open('input.mp4')
                ->export()
                ->toDisk('disk_to')
                ->inFormat(
                     (new X264('aac'))->setKiloBitrate(500)->setAudioKiloBitrate(126)
                )
                ->save('output.mp4');
```

In any case, this library uses the FFMPEG binaries. I suggest that you study FFMPEG so that you know what this library can do.

**Comment by jagdalemahesh9** [comment]
Hello,
Thanks for quick response and also information about the video


Thanks,
Mahesh Jagdale.
