### ISSUE TITLE
Laravel 8 - Installation error

### ISSUE THREAD

**Issue by thomasdseao** [protonemedia/laravel-ffmpeg#337]
Hello,

I tried to install this extension in Laravel 8 project but got errors : 

**composer require pbmedia/laravel-ffmpeg**
_Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - pbmedia/laravel-ffmpeg[7.5.0, ..., 7.5.9] require php-ffmpeg/php-ffmpeg ^0.17.0 -> satisfiable by php-ffmpeg/php-ffmpeg[v0.17.0].
    - pbmedia/laravel-ffmpeg 7.5.11 requires php-ffmpeg/php-ffmpeg ^0.18.0 -> satisfiable by php-ffmpeg/php-ffmpeg[v0.18.0].
    - pbmedia/laravel-ffmpeg 7.5.10 requires php-ffmpeg/php-ffmpeg ^0.17.0|^0.18.0 -> satisfiable by php-ffmpeg/php-ffmpeg[v0.17.0, v0.18.0].
    - php-ffmpeg/php-ffmpeg[v0.17.0, ..., v0.18.0] require doctrine/cache ^1.0 -> found doctrine/cache[v1.0, ..., 1.11.x-dev] but the package is fixed to 2.0.3 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires pbmedia/laravel-ffmpeg ^7.5 -> satisfiable by pbmedia/laravel-ffmpeg[7.5.0, ..., 7.5.11]._

I also created an Issue in php-ffmpeg project : https://github.com/PHP-FFMpeg/PHP-FFMpeg/issues/823

**Comment by thomasdseao** [comment]
Doctrine/cache is not a dependency of Laravel but from another one of my packages.
So, I removed this package and it is now working.

**Comment by pascalbaljet** [comment]
Thanks for reporting!

**Comment by stevebauman** [comment]
I also had this issue. I simply had to delete my `composer.lock` file and then re-run:

```bash
composer require pbmedia/laravel-ffmpeg
```

This was because I use Laravel's [schema migration column changes](https://laravel.com/docs/8.x/migrations#prerequisites), which requires the installation of `doctrine/dbal`.

`doctrine/dbal` requires `doctrine/cache: v1.0|v2.0`, which when installed, will use `v2.0` if you have no other dependencies using `doctrine/dbal` `v1.0`. A `composer.lock` file will then be created with the `doctrine/dbal` requirement locked at `v2.0`.

**Comment by pascalbaljet** [comment]
Fixed in v7.8.0 :)
